Repository Farama-Foundation/MO-Gymnasium, pull requests merged in 2023-02, with the labels that each got.

#25 Add mujoco reacher
  README.md
  mo_gymnasium/envs/mujoco/__init__.py
  mo_gymnasium/envs/mujoco/assets/mo_reacher.xml
  mo_gymnasium/envs/mujoco/reacher.py
  screenshots/reacher-mujoco.png
  tests/test_envs.py
Labels: enhancement

#31 Add pydoc to all environments
  README.md
  mo_gymnasium/envs/breakable_bottles/breakable_bottles.py
  mo_gymnasium/envs/continuous_mountain_car/continuous_mountain_car.py
  mo_gymnasium/envs/deep_sea_treasure/deep_sea_treasure.py
  mo_gymnasium/envs/fishwood/fishwood.py
  mo_gymnasium/envs/four_room/four_room.py
  mo_gymnasium/envs/fruit_tree/fruit_tree.py
  mo_gymnasium/envs/highway/highway.py
  mo_gymnasium/envs/lunar_lander/lunar_lander.py
  mo_gymnasium/envs/mario/mario.py
  mo_gymnasium/envs/minecart/minecart.py
  mo_gymnasium/envs/mountain_car/mountain_car.py
  mo_gymnasium/envs/mujoco/half_cheetah.py
  mo_gymnasium/envs/mujoco/hopper.py
  mo_gymnasium/envs/mujoco/reacher.py
  mo_gymnasium/envs/resource_gathering/resource_gathering.py
  mo_gymnasium/envs/water_reservoir/dam_env.py
  tests/test_envs.py
Labels: documentation, enhancement

#33 Fix highway env observation conversion
  mo_gymnasium/envs/highway/highway.py
  tests/test_envs.py
Labels: bug

#34 Add EzPickle to all envs
  mo_gymnasium/envs/breakable_bottles/breakable_bottles.py
  mo_gymnasium/envs/continuous_mountain_car/continuous_mountain_car.py
  mo_gymnasium/envs/deep_sea_treasure/deep_sea_treasure.py
  mo_gymnasium/envs/fishwood/fishwood.py
  mo_gymnasium/envs/four_room/four_room.py
  mo_gymnasium/envs/fruit_tree/fruit_tree.py
  mo_gymnasium/envs/highway/highway.py
  mo_gymnasium/envs/lunar_lander/lunar_lander.py
  mo_gymnasium/envs/mario/mario.py
  mo_gymnasium/envs/minecart/minecart.py
  mo_gymnasium/envs/mountain_car/mountain_car.py
  mo_gymnasium/envs/mujoco/half_cheetah.py
  mo_gymnasium/envs/mujoco/hopper.py
  mo_gymnasium/envs/reacher/reacher.py
  mo_gymnasium/envs/resource_gathering/resource_gathering.py
  mo_gymnasium/envs/water_reservoir/dam_env.py
  mo_gymnasium/utils.py
  tests/test_envs.py
Labels: enhancement

#37 Automatic generation of tests
  mo_gymnasium/envs/highway/__init__.py
  mo_gymnasium/envs/minecart/minecart.py
  mo_gymnasium/envs/water_reservoir/dam_env.py
  tests/test_envs.py
Labels: enhancement

#40 Improve documentation and README
  README.md
  docs/_static/videos/mo-reacher.gif
  docs/citing/citing.md
  docs/community/community.md
  docs/environments/all-environments.md
  docs/index.md
Labels: documentation

#45 Add known/approximate pareto front to Minecart and Resource Gathering
  mo_gymnasium/envs/minecart/minecart.py
  mo_gymnasium/envs/resource_gathering/resource_gathering.py
Labels: enhancement
