Repository Farama-Foundation/MO-Gymnasium, pull requests merged in 2024-08, with the labels that each got.

#97 Adding three different mo-mountain-car environments
  mo_gymnasium/envs/mountain_car/__init__.py
  mo_gymnasium/envs/mountain_car/mountain_car.py
  pyproject.toml
Labels: enhancement

#100 (Issue #99) Fix disc_episode_returns off-by-one error
  mo_gymnasium/utils.py
  tests/test_wrappers.py
Labels: bug

#101 Documentation of new Mountain Car environments
  docs/environments/classical.md
  mo_gymnasium/envs/mountain_car/mountain_car.py
Labels: documentation
